### PR TITLE
Update Learn-Back-End-Dev.md

### PR DESCRIPTION
**Pull request by kboygit**
added more resources

### CODE REVIEW

**Comment by raylu-stripe** [comment]
I'm fairly opposed to the idea of just including more stuff. There are plenty of long lists of stuff and they are all universally unhelpful. 

The value of a Google is not that it gives you the internet but that it hides the unhelpful parts. There is a lot more value in providing a small, curated list than providing tons of links. It's possible that a few people might miss out on some niche resource that would have helped them, but overall a lot more more people will find a lot more value that way.

**Comment by kboygit** [comment]
Was this too much stuff being added?

**Comment by raylu-stripe** [comment]
Yes. Maintaining this list (as links become dead) alone is going to be a pain.

To cherry-pick a few examples,
1. why is learn-rails.com linked twice?
1. is the TDD stuff actually high-quality or just inexperienced "thoughtleadership"?
1. are both of the railscasts links actually high-quality or just videos you spend time watching but don't learn anything from?
1. does libhunt have... any value whatsoever?

More generally, why would I want one of these resources over another? It's not clear why I'd click the koans one over the 100 minutes one.

**Comment by kboygit** [comment]
Ok , so more on quality not quantity.Thank you

**Pull request closed without merging**
