### PR TITLE
More resources

### PR DESCRIPTION
**Pull request by aaron-suarez**
I had to do some merge conflicts. I can only hope no resources got lost along the way... In any case, I've learned always to pull before you work, commit often, and PR just as often. Here goes.

### CODE REVIEW

**Comment by hollomancer** [comment]
@aaron-suarez - there are still a significant number of merge conflicts in these files. Let me know if you need assistance resolving.

**Comment by aaron-suarez** [comment]
@hollomancer - I don't understand, it says there's no conflicts. I can do a `git pull upstream master` and it says that I'm already up to date. Plus this is what shows on this page I'm typing on:

github-no-conflicts

**Comment by hollomancer** [comment]
Sure - take a look at the file itself.

image

This indicates that some of the merges were not resolved, or this text would not be there.

**Comment by aaron-suarez** [comment]
Huh, I see what you're saying. Is there a way to get git to tell you which files still have unresolved merges? Like I said, `git status`, `git pull`, and `git fetch` didn't tell me anything about these lines.

**Comment by aaron-suarez** [comment]
Do you need me to squash any of these commits before you merge?

**Comment by hollomancer** [comment]
Nope, I'll squash and merge.

**Pull request merged**
