### PR TITLE
Add List of Beginner Friendly Projects.

### PR DESCRIPTION
**Pull request by Programazing**
I found this managed list of beginner-friendly projects which is part of the [Awesome Project](https://github.com/sindresorhus/awesome) and thought it would be a great addition to this list.

### CODE REVIEW

**Comment by hollomancer** [comment]
@Programazing, we want to ensure that new entries to the resource list, moving forward, have a brief description of what they are. Can you add a few sentences describing what this resource is, and how it can benefit a new learner?

**Comment by Programazing** [comment]
@hollomancer Just to clarify did you want that in the current and future PRs or in the file "Get-Into-Open-Source.md" itself?

**Comment by hollomancer** [comment]
Current and future PRs.

**Comment by Programazing** [comment]
This is a list of beginner-friendly repositories. The projects listed in the repository are all various languages and have been marked by their individual creators as having Issues simple enough for beginning developers. It would benefit beginning developers by giving them an easy introduction into working with real projects on GitHub.

**Pull request merged**
